### ISSUE TITLE
Not compiling on Arduino Due

### ISSUE THREAD

**Issue by aerodolphin** [neu-rah/ArduinoMenu#101] opened 2017-07-10 22:20 UTC
```
C:\Users\aerodolphin\Desktop\Slider Project 2017\TFT\tft menu\tft2/tft2.ino:250: undefined reference to `Menu::default_serial_panel_list'

collect2.exe: error: ld returned 1 exit status

Using library SPI at version 1.0 in folder: C:\Users\aerodolphin\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\libraries\SPI 
Using library Adafruit_GFX_Library at version 1.2.1 in folder: C:\Users\aerodolphin\Documents\Arduino\libraries\Adafruit_GFX_Library 
Using library Adafruit_ST7735_Library at version 1.0.7 in folder: C:\Users\aerodolphin\Documents\Arduino\libraries\Adafruit_ST7735_Library 
Using library menu in folder: C:\Program Files (x86)\Arduino\libraries\menu (legacy)
Using library pcint in folder: C:\Program Files (x86)\Arduino\libraries\pcint (legacy)
exit status 1
Error compiling for board Arduino Due (Programming Port).`
```

**Comment by aerodolphin** [comment] 2017-07-10 22:21
I'm getting a lot of errors. Anyone have a clue of what is wrong?

**Comment by neu-rah** [comment] 2017-07-12 03:33
what was the installation method? noting that some libs are in
C:\Users\aerodolphin\Documents\Arduino\libraries\...
while the menu is at C:\Program Files (x86)\Arduino\libraries\menu (legacy)
legacy?
please install from the arduino IDE library manager and be sure to clean-up any manual installation.

**Comment by aerodolphin** [comment] 2017-07-12 08:44
I installed "menu" and "pcint" libraries manualy because they don't appear in the IDE library manager.

**Comment by aerodolphin** [comment] 2017-07-12 10:21
I saw that the correct way is to install the libraries in zip files. I will try it. I think this will solve the issues.

**Comment by neu-rah** [comment] 2017-07-12 16:13
I've installed ide 1.8.3 and both libs are listed on lib manager, please use the lib manager. key search (pcint, menu) to install both. The libs are conformant with https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#15-library-format-rev-21

and are both registered with library manager, so they should be listed, if not please let me know

**Comment by aerodolphin** [comment] 2017-07-12 19:58
Thank you. I installed the zip files of the libraries and now I can compile.

But nothing happens when I run the code on Due. Only a white screen. When I run the example "graphictest" the screen works.

I connected all iaw that example and made the change here in the code of tft:

```
#define TFT_CS   10
#define TFT_DC   8
#define TFT_RST  9
Adafruit_ST7735 gfx(TFT_CS, TFT_DC, TFT_RST);
```

I connected also the TFT to the SPI SCK and MOSI. VCC to 3.3V, GND to GND, LED- to GND and LED + to 3.3V.

Any idea?

**Comment by neu-rah** [comment] 2017-07-13 03:40
too vague... 
can you print to screen (ie on setup)?
are you calling poll on loop?

**Comment by aerodolphin** [comment] 2017-07-13 11:39
I will make a schematic of the connections.

**Comment by aerodolphin** [comment] 2017-07-13 11:40
The encoder will not work on version 3?

**Comment by aerodolphin** [comment] 2017-07-13 11:44
Yes, I have the next line in the loop:

`  nav.poll();//this device only draws when needed`

**Comment by aerodolphin** [comment] 2017-07-13 11:47
The example "tft" was unchanged. I only changed the part of the code related to the pins of the CS, D/C and RESET. They were initially to analog and I changed to digital pins.

**Comment by aerodolphin** [comment] 2017-07-13 11:49
Is there anyway to test what is wrong?

**Comment by aerodolphin** [comment] 2017-07-13 11:58
Maybe can be related to this issue:
[Issue #81](https://github.com/neu-rah/ArduinoMenu/issues/81)

**Comment by neu-rah** [comment] 2017-07-13 13:02
> The example "tft" was unchanged. I only changed the part of the code related to the pins of the CS, D/C and RESET. They were initially to analog and I changed to digital pins.

you can check if its really this change by changing back... and if it is then you can try to select other pins.

PCINT only works on ports B, C, D (because it was ported from Atmega328p)

if there is any problem with due + encoder please let me know... preferably on another issue to keep things easy for future reference

**Comment by aerodolphin** [comment] 2017-07-13 13:09
Yesterday I tried also on the analog ports (unchanged). Same issue, a blankscreen.

Regarding to the PCINT. I don't understand what are the ports B, C and D.

About encoder, I will have to test when I saw the menu on the screen.

**Comment by aerodolphin** [comment] 2017-07-13 13:17
The ports B, C and D are the microprocessor ports? What are the corresponding ones in the arduino Due?

```
Board | Digital Pins Usable For Interrupts
Uno, Nano, Mini, other 328-based | 2, 3
Mega, Mega2560, MegaADK | 2, 3, 18, 19, 20, 21
Micro, Leonardo, other 32u4-based | 0, 1, 2, 3, 7
Due | all digital pins
101 | all digital pins
```

**Comment by neu-rah** [comment] 2017-07-13 13:44
Not using interrupts but using pin change interrupts, PinChangeInterrupts are available for many pins.
http://www.robgray.com/temp/Due-pinout-WEB.png
pale yellow (legend: port/pin) tells the needed Port

**Comment by aerodolphin** [comment] 2017-07-13 14:01
Ok. Din't know about PinChangeInterrupts.

Only the pins of the encoder have to be connected to those ports (B, C or D)? Or also the ports for the CS, D/C and RST?

Pins from the encoders are ok (D2 PIN - B.25, D3 - C.28 and D4, B.25).
If CS, D/C and RST has to be connected to those ports. If we use A0, A1 and A2 they will be connected to the A ports.

So, I think the problem is in another place

**Comment by neu-rah** [comment] 2017-07-13 14:46
port like [B.17] or [C.12] where the letter indicates the port and number. on ATMega328 there are 8 pins per port max. the same limit applies to due even if ports have more than 8 pins (because of the demultiplexing tables).... the PCINT library example can print a pin map.

encoders can use an alternative driver (clickEncoder) that uses timers instead of PCINT (have to install click encoder and timer1 libs)

**Comment by aerodolphin** [comment] 2017-07-14 00:08
`void setup() {
  options=&myOptions;
  pinMode(LEDPIN,OUTPUT);
  Serial.begin(115200);
  while(!Serial);
  Serial.println("menu 3.0 test");
  Serial.flush();
  nav.idleTask=idle;//point a function to be used when menu is suspended
  mainMenu[1].enabled=disabledStatus;
  //outGfx.usePreview=true;//reserve one panel for preview?
  //nav.showTitle=false;//show menu title?

  //pinMode(encBtn, INPUT_PULLUP);
  encButton.begin();
  encoder.begin();

  SPI.begin();
  gfx.initR(INITR_BLACKTAB);
  gfx.setRotation(3);
  gfx.setTextSize(textScale);//test scalling
  gfx.setTextWrap(false);
  gfx.fillScreen(ST7735_BLACK);
  gfx.setTextColor(ST7735_RED,ST7735_BLACK);
  gfx.println("Menu 3.x test on GFX");
  delay(1000);
}`

In void setup() I removed the two lines of the encoder:
```
  //encButton.begin();
  //encoder.begin();
```

And now I can see the menu on display.
So, the problem is in the encoder part.

I changed the pins for the encoder to:

```
// rotary encoder pins
#define encA    36 // C.4
#define encB    34 // C.2
#define encBtn  30 // D.9
```

Now the ports are in the (B, C or D) and the numbers are less than 8. It's correct, right?

I will try to make some more tests with the encoder.

**Comment by aerodolphin** [comment] 2017-07-14 00:38
I tried the next example and I can't make it work.

```
#include <pcint.h>

#define led 13
#define btn 30

void setled() {
  digitalWrite(led,digitalRead(btn));
}

void setup() {
  pinMode(led,OUTPUT);
  pinMode(btn,INPUT_PULLUP);
  PCattachInterrupt<btn>(setled,CHANGE);
  setled();//initial led status
}

void loop() {}

```

**Comment by aerodolphin** [comment] 2017-07-14 14:04
I tried several pins and the LED didn't turn on. I also put a pull up resistor and nothing.

Any ideas why this PCINT simple example don't work with Arduino Due?

**Comment by neu-rah** [comment] 2017-07-14 14:05
on atmega328 the led pin is also used by spi... but the looking at due pinout it does not seem so... i will try with my due.

**Comment by aerodolphin** [comment] 2017-07-14 14:16
Ok. Thanks for the help. I will wait your test.

**Comment by neu-rah** [comment] 2017-07-14 14:21
i can confirm it does not work on due, even with no other devices attached or using some other btn pins like 11, this looks like a lib bug... investigating

**Comment by aerodolphin** [comment] 2017-07-14 14:30
ok

**Comment by neu-rah** [comment] 2017-07-14 17:17
fixed PCINT bug on due, resulting on call of uninitialized function call
https://github.com/neu-rah/PCINT/commit/6b4df143d659fe394223785481fb149de6fbb703#diff-af8a6206c4eff4ac03c1b8ad758fe971R105
 was able to run the btnled example

no restriction for ports or pins (sorry those mentioned restrictions were for atmega1284 and 2560)
for due pcint is implemented as normal interrupts because due supports them on any pin.

unfortunately there was a bug, missing an initialization... hope its fixed now.

thanks for you patience and help by reporting it :D

**Comment by aerodolphin** [comment] 2017-07-15 18:58
Thanks. It's working now.

**Closed** 2017-07-15 19:57 UTC
